name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: gcp-peoject-1
      GCR_IMAGE: gcr.io/gcp-peoject-1/your-gcp-image-name
      SERVICE_NAME: my-cloud-run-service

    steps:

    # 1. Checkout your repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        project_id: ${{ env.GCP_PROJECT_ID }}

    # 3. Build and push Docker image to Google Container Registry (GCR)
    - name: Build and Push Docker Image to GCR
      run: |
        gcloud builds submit --tag $GCR_IMAGE

    # 4. Deploy the application to Google Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $GCR_IMAGE \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
