name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: gcp-peoject-1
      GCR_IMAGE: gcr.io/gcp-peoject-1/your-gcp-image-name
      SERVICE_NAME: demo-service

    steps:

    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    # Step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    # Step 4: Build and Push the Docker Image to Google Container Registry (GCR)
    - name: Build and Push Docker Image to GCR
      run: |
        gcloud builds submit --tag $GCR_IMAGE

    # Step 5: Deploy the service to Google Cloud Run
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $GCR_IMAGE \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
