name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 17 (using Temurin distribution)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install -Pproduction

      # Set up Google Cloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
        #  project_id: ${{ secrets.GCP_PROJECT_ID }}
          project_id: gcp-peoject-1

      # Authenticate to Google Cloud using service account
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SECONDPROJECT }}

      # Configure Docker to authenticate with Google Cloud Artifact Registry
      - name: Configure Docker to use gcloud credentials
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/gcp-peoject-1/second-repo/testapp .

      # Push Docker Image to Artifact Registry
      - name: Push Docker Image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/gcp-peoject-1/second-repo/testapp

      # Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy second-service \
            --image us-central1-docker.pkg.dev/gcp-peoject-1/second-repo/testapp \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
