name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        project_id: gcp-peoject-1  # Replace with your actual project ID

    - name: Build and Push to GCP
      run: |
        gcloud builds submit --tag gcr.io/gcp-peoject-1/image-name

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy service-name \
          --image gcr.io/gcp-peoject-1/image-name \
          --region us-central1 \
          --platform managed
